"""take away extra on user

Revision ID: 23e037d8ddc8
Revises: 7c04edf78057
Create Date: 2023-05-08 21:16:20.661160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e037d8ddc8'
down_revision = '7c04edf78057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
