"""added back img link

Revision ID: cd91b22e0dfd
Revises: 23e037d8ddc8
Create Date: 2023-05-11 05:57:55.334220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd91b22e0dfd'
down_revision = '23e037d8ddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_front', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_back', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_back')
        batch_op.drop_column('image_front')

    # ### end Alembic commands ###
